import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { AuthProvider } from "@/app/context/AuthContext"; 
import { LocationProvider } from "./context/LocationContext";
import { SnackProvider } from "./context/SnackContext";
import { BookingProvider } from "./context/BookingContext";
import ClientLayout from "./ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "buzzbook",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen flex flex-col bg-gray-900 text-white font-sans antialiased">
        <AuthProvider>
          <LocationProvider>
            <BookingProvider>
              <SnackProvider>
            
                <ClientLayout>{children}</ClientLayout>

                <Toaster richColors position="top-right" />

              </SnackProvider>
            </BookingProvider>
          </LocationProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
