import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import { StatsProvider } from "./context/statsContext";
import { MovieProvider } from "./context/movieContext";
import { TheaterProvider } from "./context/theaterContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "buzzbook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StatsProvider>
          <TheaterProvider>
            <MovieProvider>
              {children}
              <Toaster richColors position="top-right" />
            </MovieProvider>
          </TheaterProvider>
        </StatsProvider>
      </body>
    </html>
  );
}
